services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    expose:
      - 8088
    ports:
      - "80:8088"
    volumes:
      - ./wallsite/staticfiles:/app/www/wallsite/static
      - ./wallsite/media:/app/www/wallsite/media
      - ./wallsite/logs:/app/www/wallsite/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - wallsite
  wallsite:
    build: ./wallsite
    image: wallsite
    container_name: wallsite
    restart: always
    command: 'gunicorn -c gunicorn.py wallsite.wsgi'
    env_file:
      - .env
    links:
      - 'postgres:dbps'
    networks:
      - dbnet
    volumes:
      - ./wallsite:/app/www/wallsite
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    links:
      - 'postgres:db'
    networks:
      - dbnet
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data: