# Generated by Django 6.0.8 on 2026-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0002_wall_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='private',
            field=models.BooleanField(verbose_name='Опубликовать анонимно'),
        ),
    ]
