# Generated by Django 6.0.8 on 2026-08-22 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0003_alter_wall_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Лайки', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнувшие пользователи'),
        ),
    ]
